version: "2"

services:
  database:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./model-database/src/main/resources/com/bnorm/barkeep/db/init:/docker-entrypoint-initdb.d
