version: '2'
services:

  database:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./database/init:/docker-entrypoint-initdb.d

  service:
    image: barkeep/barkeep-service
    ports:
    - "8080:8080"
    environment:
    - barkeep.db.host=database
    links:
    - database
