#server:
#  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false

zuul:
  routes:
    ingredients:
      path: /ingredient-service/**
      serviceId: INGREDIENT-SERVICE
    recipes:
      path: /recipe-service/**
      serviceId: RECIPE-SERVICE